"""Tests for setting up and unloading the MyJDownloader integration."""

from unittest.mock import MagicMock

from myjdapi.exception import MYJDConnectionException
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.myjdownloader.const import DOMAIN
from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr, entity_registry as er

DEVICE_ID = "af9d03a21ddb917492dc1af8a6427f11"

# unique_ids as generated by v2.5.0. They embed the display name (with spaces),
# which the entry migration in the modernization has to map to stable ids.
LEGACY_UNIQUE_IDS = {
    "sensor.jdownloaders_online": "myjdownloader_JDownloaders Online_sensor_number",
    "sensor.jdownloader_mypc_status": "myjdownloader_JDownloader MyPC Status_sensor_status",
    "sensor.jdownloader_mypc_download_speed": "myjdownloader_JDownloader MyPC Download Speed_sensor_download_speed",
    "sensor.jdownloader_mypc_packages": "myjdownloader_JDownloader MyPC Packages_sensor_packages",
    "sensor.jdownloader_mypc_links": "myjdownloader_JDownloader MyPC Links_sensor_links",
    "switch.jdownloader_mypc_pause": "myjdownloader_JDownloader MyPC Pause_switch_pause",
    "switch.jdownloader_mypc_limit": "myjdownloader_JDownloader MyPC Limit_switch_limit",
    "update.jdownloader_mypc_update": "myjdownloader_JDownloader MyPC Update_update",
}


async def test_setup_and_unload(
    hass: HomeAssistant, init_integration: MockConfigEntry
) -> None:
    """Test the entry is set up and unloaded."""
    entry = init_integration
    assert entry.state is ConfigEntryState.LOADED
    assert hass.services.has_service(DOMAIN, "add_links")

    assert await hass.config_entries.async_unload(entry.entry_id)
    await hass.async_block_till_done()
    assert entry.state is ConfigEntryState.NOT_LOADED
    assert not hass.services.has_service(DOMAIN, "add_links")


async def test_setup_not_ready(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry, mock_myjdapi: MagicMock
) -> None:
    """Test a connection error during setup schedules a retry."""
    mock_myjdapi.connect.side_effect = MYJDConnectionException("offline")
    mock_config_entry.add_to_hass(hass)
    await hass.config_entries.async_setup(mock_config_entry.entry_id)
    await hass.async_block_till_done()
    assert mock_config_entry.state is ConfigEntryState.SETUP_RETRY


async def test_legacy_entities(
    hass: HomeAssistant,
    init_integration: MockConfigEntry,
    device_registry: dr.DeviceRegistry,
    entity_registry: er.EntityRegistry,
) -> None:
    """Record the v2.5.0 entity and unique_id layout (migration baseline)."""
    # async_get_device is deprecated in 2026.9, its replacement only exists since
    # 2026.8; listing by config entry works on every supported version.
    devices = dr.async_entries_for_config_entry(
        device_registry, init_integration.entry_id
    )
    assert len(devices) == 1
    device = devices[0]
    assert device.identifiers == {(DOMAIN, DEVICE_ID)}
    assert device.name == "JDownloader MyPC"

    entries = er.async_entries_for_config_entry(
        entity_registry, init_integration.entry_id
    )
    assert {e.entity_id: e.unique_id for e in entries} == LEGACY_UNIQUE_IDS
    for entity in entries:
        if entity.entity_id != "sensor.jdownloaders_online":
            assert entity.device_id == device.id

    assert hass.states.get("sensor.jdownloader_mypc_status").state == "running"
    assert hass.states.get("sensor.jdownloader_mypc_download_speed").state == "2.5"
    assert hass.states.get("switch.jdownloader_mypc_limit").state == "off"
