restart_and_update:
  target:
    device:
      integration: myjdownloader
run_update_check:
  target:
    device:
      integration: myjdownloader
start_downloads:
  target:
    device:
      integration: myjdownloader
stop_downloads:
  target:
    device:
      integration: myjdownloader
