add_links:
  fields:
    device_id:
      required: true
      selector:
        device: &jdownloader_device
          filter:
            integration: myjdownloader
          entity:
            - integration: myjdownloader
              domain: button
    links:
      required: true
      example: "https://example.org/file.zip"
      selector:
        text:
          multiple: true
    autostart:
      required: false
      example: false
      default: false
      selector:
        boolean:
    package_name:
      required: false
      example: "My Download Package"
      selector:
        text:
    priority:
      required: true
      example: "default"
      default: "default"
      selector:
        select:
          translation_key: "priority"
          options:
            - highest
            - higher
            - high
            - default
            - low
            - lower
            - lowest
    download_password:
      required: false
      selector:
        text:
          type: password
    extract_password:
      required: false
      selector:
        text:
          type: password
    auto_extract:
      required: false
      example: false
      default: false
      selector:
        boolean:
    destination_folder:
      required: false
      advanced: true
      example: "/home/ubuntu/Downloads"
      selector:
        text:
    overwrite_packagizer_rules:
      required: false
      advanced: true
      example: false
      default: false
      selector:
        boolean:
restart_and_update:
  fields:
    device_id:
      required: true
      selector:
        device: *jdownloader_device
run_update_check:
  fields:
    device_id:
      required: true
      selector:
        device: *jdownloader_device
start_downloads:
  fields:
    device_id:
      required: true
      selector:
        device: *jdownloader_device
stop_downloads:
  fields:
    device_id:
      required: true
      selector:
        device: *jdownloader_device
